### ISSUE TITLE
Bổ sung option ttl khi xử lý command line

### ISSUE THREAD

**Issue by anhldbk** [chaunm/znp-service#1]
`ttl` là thời gian định kỳ mà service phải gửi event `:event/status` (Xem thêm tại [Common Actor](https://github.com/anhldbk/node-actors-prototype/blob/master/actors/actor-system.md#24-event)

Anh bổ sung phần tham số `--ttl` khi xử lý command line vào nhé! Nếu không có thì để mặc định `ttl = 20s`

**Comment by chaunm** [comment]
Đã bổ sung chức năng này
