### ISSUE TITLE
New mechanism for logging

### ISSUE THREAD

**Issue by anhldbk** [chaunm/znp-service#3]
We're using `Fluentd` as a new logging platform.

Please rewrite your log function using [fluent-logger-c](https://github.com/roadman/fluent-logger-c) asap

**Comment by anhldbk** [comment]
@chaunm Pls have a look at a Nodejs implementation: https://github.com/anhldbk/node-actors/blob/master/lib/core/util/advanced-logger.js

**Comment by chaunm** [comment]
Completed
